package myThread.org;
class Bracket{
	

	synchronized static public void generate(String threadCode)
	{
		for(int i = 1;i<=10;i++)
		{
//			try {
//				Thread.sleep(100);
//			}catch(InterruptedException e)
//			{
//				e.printStackTrace();
//			}
			if(i<=5)
			{
				System.out.print("[");
			}
			else
			{
				System.out.print("]");
			}
		}
		System.out.println("Generated By Thread: " +threadCode);
	}
}
public class staticSync {
	
  public static void main(String[] args)
  {
//	  Bracket b1 = new Bracket("Thread 1");
//	  Bracket b2 = new Bracket("Thread 2");
	  //b1.generate();
	  new Thread(new Runnable() {
		  public void run()
		  {
			  for(int i = 1;i<=5;i++)
			  {
				  Bracket.generate("Thread 1");
			  }
		  }
	  }).start();
	  
	  new Thread(new Runnable() {
		  public void run()
		  {
			  for(int i = 1;i<=5;i++)
			  {
				  Bracket.generate("Thread 2");
			  }
		  }
	  }).start();
  }
}
